In this notebook we will learn Basics of tensorflow.

* Introduction to tensor
* Getting Information from tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular python)
* Using GPUs with tensorFlow.


In [ ]:
# Import tensorflow

import tensorflow as tf
import numpy as np
import pandas as pd
print(tf.__version__)

2.19.0


In [ ]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the no of dimensions (ndim is for number of dimensions)
scalar.ndim

In [ ]:
# Create a vector. Here, we pass a list.
vector = tf.constant([10,10])
vector

In [ ]:
# Check the dimension of vector
vector.ndim

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
# Create a matrix and specify the dtype
matrix1 = tf.constant([[10.,7.],
                       [3.,2.],
                        [8.,9.]],dtype=tf.float16)
matrix1

In [ ]:
matrix1.ndim

2

In [ ]:
# Create a 3D tensor
# shape=(3, 2, 3): Three tensors, each has 2-Rows and 3-Columns
tensor_3d = tf.constant([[[1, 2, 3],
                         [4, 5, 6]],
                        [[7, 8, 9],
                         [10, 11, 12]],
                         [[14, 15, 16],
                         [17, 18, 19]]])
display(tensor_3d)

In [ ]:
tensor_3d.ndim

3

What we have created so far

* A scalar is a single number.
* Vector: A number with direction.
* Matrix: a 2-dimensional array of numbers

* Tensor: an n-dimensional array of numbers where n can be any number, a 0 dimensional tensor is scalar.

In [ ]:
tf.Variable

In [ ]:
# Create the same tensor with Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

In [ ]:

changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# The assignment will result in an error
changeable_tensor[0] = 7
changeable_tensor

In [ ]:
# Even with assign() we cannot change unchangeable Matrix
# The following will throw an error.
unchangeable_tensor[0].assign(7)
unchangeable_tensor

 **Note:** Rarely in practice will we decide wither to use tf.constant or tf.Variable as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

#Creating Random Tensors

* Random tensors are tensors of arbitary size which contain random numbers.

* A neural network starts with random values for their weights.





In [ ]:
# creating random tensors.
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

# Shuffle the order of elements in a Tensor

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

# Shuffle the above. Shuffles the tensors along the ROW. Rows are shuffled.
tf.random.shuffle(not_shuffled)


In [ ]:
tf.random.set_seed(42) # Global Tensors
tf.random.shuffle(not_shuffled, seed=42) # Operation Level Random Seed.

# Creating Tensors from Numpy

In [ ]:
tf.ones(shape=(3,4))

In [ ]:
tf.zeros(shape=(3,4))

### Turn numpy arrays into numbers.
Main difference between Numpy Arrays and Tensors is that Tensors can be run effectively on GPU.

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

# Converting above numpy array to tensors
A = tf.constant(numpy_A, shape=(2,3,4))
A

In [ ]:
B = tf.constant(numpy_A, shape=(3,8))
B

### Getting Information From Tensors

At times you might want to extract more information from tensors.

* Shape: Length of elements.
* Rank:  Number of dimensions. Scalar is Rank 0, Vector is rank 1 and Matrix is Rank 2 (Rows * Columns).

In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
# shape = (2,3,4,5)
# 2 Large containers then inside these 2 containers 3 other containers.
# Inside these 3 containers we have a 4 * 5 Matrix
rank_4_tensor

In [ ]:
print("Datatype of every element is:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of Tensor is :", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))

In [ ]:
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
# All Rows and Last Column
rank_2_tensor[:,-1]

In [ ]:
# The ... means all dimensions plus a new axis
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
rank_2_tensor.shape, rank_3_tensor.shape

# Basic Tensor Operations

In [ ]:
random_tensor = tf.constant([[10,7],
                             [3,4]])
random_tensor + 10

In [ ]:
random_tensor * 10

In [ ]:
tf.multiply(random_tensor, random_tensor)

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
tf.multiply(X,Y)

In [ ]:
z = tf.multiply(X,Y)
tf.reshape(z, shape=(2,3))

## Dot Product vs. Matrix Multiplication

The dot product and matrix multiplication are related but distinct operations.

**Dot Product:**

*   The dot product is an operation on two equal-length sequences of numbers.
*   It results in a single scalar value.
*   Geometrically, it's the product of the Euclidean magnitudes of the two vectors and the cosine of the angle between them.

**Matrix Multiplication:**

*   Matrix multiplication is an operation on two matrices.
*   It results in a new matrix.
*   For matrix multiplication to be possible, the number of columns in the first matrix must equal the number of rows in the second matrix.
*   Each element in the resulting matrix is the dot product of a row from the first matrix and a column from the second matrix.

In [ ]:
# Example of Dot Product
vector_a = tf.constant([1, 2, 3])
vector_b = tf.constant([4, 5, 6])

dot_product = tf.reduce_sum(vector_a * vector_b)
print("Dot Product:", dot_product)

In [ ]:
# Example of Matrix Multiplication
matrix_a = tf.constant([[1, 2],
                        [3, 4]])
matrix_b = tf.constant([[5, 6],
                        [7, 8]])

matrix_multiply = tf.matmul(matrix_a, matrix_b)
print("Matrix Multiplication Result:")
display(matrix_multiply)

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.transpose(X)

In [ ]:
tf.matmul(tf.transpose(X), Y)

In [ ]:
F = tf.constant(np.random.random(10))
F, tf.argmax(F), tf.argmin(F)